#include "main.h"
#include <stdio.h>
#include <stdlib.h>
#include <wchar.h>

// Global variables for compiler state
static int compiler_initialized = 0;
static int error_count = 0;
static wchar_t* last_error_message = NULL;
static wchar_t* last_source_code = NULL;
static wchar_t* last_mips_code = NULL;
static wchar_t* last_parse_tree = NULL;
static wchar_t* last_ast = NULL;
static wchar_t* last_symbol_table = NULL;

// Compiler initialization and cleanup
COMPILERCORE_API int initCompiler(void) {
    if (compiler_initialized) {
        return 1; // Already initialized
    }
    
    // Initialize compiler state
    error_count = 0;
    last_error_message = NULL;
    last_source_code = NULL;
    last_mips_code = NULL;
    last_parse_tree = NULL;
    last_ast = NULL;
    last_symbol_table = NULL;
    
    compiler_initialized = 1;
    return 1; // Success
}

COMPILERCORE_API void freeCompiler(void) {
    if (!compiler_initialized) {
        return;
    }
    
    // Free allocated memory
    if (last_error_message) {
        free(last_error_message);
        last_error_message = NULL;
    }
    if (last_source_code) {
        free(last_source_code);
        last_source_code = NULL;
    }
    if (last_mips_code) {
        free(last_mips_code);
        last_mips_code = NULL;
    }
    if (last_parse_tree) {
        free(last_parse_tree);
        last_parse_tree = NULL;
    }
    if (last_ast) {
        free(last_ast);
        last_ast = NULL;
    }
    if (last_symbol_table) {
        free(last_symbol_table);
        last_symbol_table = NULL;
    }
    
    compiler_initialized = 0;
}

// Source code compilation
COMPILERCORE_API int compileSourceCode(const wchar_t* sourceCode) {
    if (!compiler_initialized) {
        return 0; // Not initialized
    }
    
    if (!sourceCode) {
        error_count = 1;
        return 0; // Invalid input
    }
    
    // Store source code
    if (last_source_code) {
        free(last_source_code);
    }
    size_t len = wcslen(sourceCode) + 1;
    last_source_code = (wchar_t*)malloc(len * sizeof(wchar_t));
    if (last_source_code) {
        wcscpy(last_source_code, sourceCode);
    }
    
    // Simulate compilation (for now, just generate sample output)
    error_count = 0;
    
    // Generate sample parse tree
    if (last_parse_tree) {
        free(last_parse_tree);
    }
    last_parse_tree = (wchar_t*)malloc(1000 * sizeof(wchar_t));
    if (last_parse_tree) {
        wcscpy(last_parse_tree, L"برنامج\n├── [\n│   ├── متغيرات\n│   │   └── متغير صحيح\n│   └── ]\n└── :\n    └── اطبع متغير\n");
    }
    
    // Generate sample AST
    if (last_ast) {
        free(last_ast);
    }
    last_ast = (wchar_t*)malloc(1000 * sizeof(wchar_t));
    if (last_ast) {
        wcscpy(last_ast, L"Program\n├── Block\n│   ├── Variables\n│   │   └── Variable(int)\n│   └── Statements\n│       └── PrintStatement\n│           └── VariableReference\n");
    }
    
    // Generate sample MIPS code
    if (last_mips_code) {
        free(last_mips_code);
    }
    last_mips_code = (wchar_t*)malloc(2000 * sizeof(wchar_t));
    if (last_mips_code) {
        wcscpy(last_mips_code, L"# MIPS Assembly Code\n# Generated by Arabic Compiler\n\n.text\n.globl main\n\nmain:\n    # Initialize variables\n    li $t0, 42\n    \n    # Print variable\n    move $a0, $t0\n    li $v0, 1\n    syscall\n    \n    # Exit program\n    li $v0, 10\n    syscall\n\n.data\n");
    }
    
    // Generate sample symbol table
    if (last_symbol_table) {
        free(last_symbol_table);
    }
    last_symbol_table = (wchar_t*)malloc(1000 * sizeof(wchar_t));
    if (last_symbol_table) {
        wcscpy(last_symbol_table, L"Symbol Table:\n├── متغير (Variable)\n│   ├── Type: صحيح (int)\n│   ├── Scope: Global\n│   └── Address: $t0\n└── Total Symbols: 1\n");
    }
    
    return 1; // Success
}

// Error handling
COMPILERCORE_API int getErrorCount(void) {
    return error_count;
}

COMPILERCORE_API int getErrorMessages(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0) {
        return 0;
    }
    
    if (error_count == 0) {
        wcscpy(buffer, L"No errors");
        return 1;
    }
    
    if (last_error_message) {
        wcsncpy(buffer, last_error_message, bufferSize - 1);
        buffer[bufferSize - 1] = L'\0';
    } else {
        wcscpy(buffer, L"Unknown error");
    }
    
    return 1;
}

COMPILERCORE_API int getLexicalErrors(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0) {
        return 0;
    }
    
    wcscpy(buffer, L"No lexical errors");
    return 1;
}

COMPILERCORE_API int getSyntaxErrors(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0) {
        return 0;
    }
    
    wcscpy(buffer, L"No syntax errors");
    return 1;
}

COMPILERCORE_API int getSemanticErrors(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0) {
        return 0;
    }
    
    wcscpy(buffer, L"No semantic errors");
    return 1;
}

// Parse tree access
COMPILERCORE_API int getParseTree(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0 || !last_parse_tree) {
        return 0;
    }
    
    wcsncpy(buffer, last_parse_tree, bufferSize - 1);
    buffer[bufferSize - 1] = L'\0';
    return 1;
}

COMPILERCORE_API int exportParseTreeToDot(const wchar_t* filename) {
    if (!filename) {
        return 0;
    }
    
    // For now, just return success
    return 1;
}

COMPILERCORE_API int exportParseTreeToXML(const wchar_t* filename) {
    if (!filename) {
        return 0;
    }
    
    // For now, just return success
    return 1;
}

COMPILERCORE_API int exportParseTreeToJSON(const wchar_t* filename) {
    if (!filename) {
        return 0;
    }
    
    // For now, just return success
    return 1;
}

// AST access
COMPILERCORE_API int getAST(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0 || !last_ast) {
        return 0;
    }
    
    wcsncpy(buffer, last_ast, bufferSize - 1);
    buffer[bufferSize - 1] = L'\0';
    return 1;
}

COMPILERCORE_API int exportASTToDot(const wchar_t* filename) {
    if (!filename) {
        return 0;
    }
    
    // For now, just return success
    return 1;
}

COMPILERCORE_API int exportASTToXML(const wchar_t* filename) {
    if (!filename) {
        return 0;
    }
    
    // For now, just return success
    return 1;
}

// Symbol table access
COMPILERCORE_API int getSymbolTable(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0 || !last_symbol_table) {
        return 0;
    }
    
    wcsncpy(buffer, last_symbol_table, bufferSize - 1);
    buffer[bufferSize - 1] = L'\0';
    return 1;
}

COMPILERCORE_API int exportSymbolTableToCSV(const wchar_t* filename) {
    if (!filename) {
        return 0;
    }
    
    // For now, just return success
    return 1;
}

// MIPS code generation
COMPILERCORE_API int getMIPSCode(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0 || !last_mips_code) {
        return 0;
    }
    
    wcsncpy(buffer, last_mips_code, bufferSize - 1);
    buffer[bufferSize - 1] = L'\0';
    return 1;
}

COMPILERCORE_API int saveMIPSCodeToFile(const wchar_t* filename) {
    if (!filename) {
        return 0;
    }
    
    // For now, just return success
    return 1;
}

// Variable and procedure information
COMPILERCORE_API int getVariableInfo(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0) {
        return 0;
    }
    
    wcscpy(buffer, L"Variables:\n├── متغير (int)\n│   ├── Scope: Global\n│   └── Address: $t0\n└── Total Variables: 1\n");
    return 1;
}

COMPILERCORE_API int getProcedureInfo(wchar_t* buffer, int bufferSize) {
    if (!buffer || bufferSize <= 0) {
        return 0;
    }
    
    wcscpy(buffer, L"Procedures:\n└── main\n    ├── Type: void\n    ├── Parameters: 0\n    └── Local Variables: 1\n");
    return 1;
}

// Compiler statistics
COMPILERCORE_API int getTokenCount(void) {
    return 15; // Sample token count
}

COMPILERCORE_API int getParseTreeNodeCount(void) {
    return 8; // Sample node count
}

COMPILERCORE_API int getASTNodeCount(void) {
    return 6; // Sample AST node count
}

COMPILERCORE_API int getSymbolCount(void) {
    return 1; // Sample symbol count
}

COMPILERCORE_API int getMIPSInstructionCount(void) {
    return 8; // Sample instruction count
}

// Compiler options
COMPILERCORE_API int setCompilerOption(const wchar_t* option, const wchar_t* value) {
    if (!option || !value) {
        return 0;
    }
    
    // For now, just return success
    return 1;
}

COMPILERCORE_API int getCompilerOption(const wchar_t* option, wchar_t* buffer, int bufferSize) {
    if (!option || !buffer || bufferSize <= 0) {
        return 0;
    }
    
    // For now, return default values
    if (wcscmp(option, L"optimization") == 0) {
        wcscpy(buffer, L"enabled");
    } else if (wcscmp(option, L"debug") == 0) {
        wcscpy(buffer, L"enabled");
    } else {
        wcscpy(buffer, L"default");
    }
    
    return 1;
}
